apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: serverless-index
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serverless-index
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: serverless-index
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: serverless-index
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: serverless-index
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/serverless-index@sha256:8af8e5635ca3425b2f2e93e81e997ad0c7fc5e9d5773902289e83d39235b8f38
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
