apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: knative-serving-controller
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-serving-controller@sha256:5f02824bf405b6dfa194808657bf294e5ba4662193443c06ce524e48bff84d4f
        name: container-image
        resources: {}
status: {}
