apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-eventing-pong
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-eventing-pong
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-eventing-pong
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-eventing-pong
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-eventing-pong
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-eventing-pong@sha256:85be52fd12f22dd4927ee2e5ccf554a56fcd5238f691754d2c55435d5e9555ff
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
