apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-eventing-kafka-broker-post-install
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-eventing-kafka-broker-post-install
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-eventing-kafka-broker-post-install
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-eventing-kafka-broker-post-install
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-eventing-kafka-broker-post-install
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-eventing-kafka-broker-post-install@sha256:480943629158c8e28c3886a1d6a8d4dcf7a6195687d504c6a23c3224d8696b5e
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
