apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-serving-dataplane-probe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-serving-dataplane-probe
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-serving-dataplane-probe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-serving-dataplane-probe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-serving-dataplane-probe
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-serving-dataplane-probe@sha256:b843ed3c812dbb4204b0de5dee0f9a5eee1e82dbe36b96bcc43626a82f4b859c
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
