apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: knative-serving-activator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-serving-activator@sha256:7650aea67c00cb83c5c41dc50c384c2d129580c988c625057a9ac17ea3dd911b
        name: container-image
        resources: {}
status: {}
