apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-eventing-schema
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-eventing-schema
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-eventing-schema
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-eventing-schema
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-eventing-schema
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-eventing-schema@sha256:c6e874b9a96803029746a2ddb5cc9deaf27bfbc766d19643ea81a109f5450b1c
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
