apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: net-kourier-kourier
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: net-kourier-kourier
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: net-kourier-kourier
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: net-kourier-kourier
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: net-kourier-kourier
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/net-kourier-kourier@sha256:0a88c4811008bf9b8cd62abc8f077593fc46b5ceaf9552e2d12c99c3acfa6c30
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
