apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-eventing-kafka-broker-event-display
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-eventing-kafka-broker-event-display
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-eventing-kafka-broker-event-display
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-eventing-kafka-broker-event-display
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-eventing-kafka-broker-event-display
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-eventing-kafka-broker-event-display@sha256:8b08c2764f29e138a7dac00a951f2a8329320c62e72ab1da0f0eb9b072d06d96
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
