apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-eventing-kafka-broker-kafka-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-eventing-kafka-broker-kafka-controller
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-eventing-kafka-broker-kafka-controller
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-eventing-kafka-broker-kafka-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-eventing-kafka-broker-kafka-controller
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-eventing-kafka-broker-kafka-controller@sha256:4ab3e992adc0e7ec99c3e2ca2c10e70cd12f9d8850b1ac66f4cf384c1430f771
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
