apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: net-istio-webhook
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/net-istio-webhook@sha256:0d94ec81565f8fddd5bf6477a5c03e88896719b77fae1d7350155cb44b8ec9c1
        name: container-image
        resources: {}
status: {}
