apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-serving-autoscaler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-serving-autoscaler
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-serving-autoscaler
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-serving-autoscaler
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-serving-autoscaler
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-serving-autoscaler@sha256:41d8a7ff5d750c4f7f041e8ff74814e0911b2410ed3412e18143ddfb8b47660e
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
