apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-serving-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-serving-controller
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-serving-controller
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-serving-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-serving-controller
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-serving-controller@sha256:5f02824bf405b6dfa194808657bf294e5ba4662193443c06ce524e48bff84d4f
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
