apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-eventing-kafka-broker-webhook-kafka
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-eventing-kafka-broker-webhook-kafka
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-eventing-kafka-broker-webhook-kafka
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-eventing-kafka-broker-webhook-kafka
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-eventing-kafka-broker-webhook-kafka
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
