apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-serving-activator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-serving-activator
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-serving-activator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-serving-activator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-serving-activator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-serving-activator@sha256:7650aea67c00cb83c5c41dc50c384c2d129580c988c625057a9ac17ea3dd911b
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
