apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: net-istio-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: net-istio-controller
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: net-istio-controller
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: net-istio-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: net-istio-controller
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/net-istio-controller@sha256:31234c7f85a11ac0e36f2192f7189882cc8b5e524d57468fa6d17d5d178b2126
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
