apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-serving-queue
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-serving-queue
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-serving-queue
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-serving-queue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-serving-queue
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-serving-queue@sha256:c3e739a6ac6a806a1b1391f4e20f60f2cc0f2cd90e96385ce8d9474d8540ef9e
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
